name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
